
package:
    name: rootsys
    version: 5.34.23

source:
    git_url: https://github.com/root-mirror/root
    git_tag: v5-34-23

build:
    number: 0

requirements:
    build:
        - python
        - openssl
        - sqlite
        - cmake
        - qt
        - fftw
        - libxml2
        - gccxml
        - pcre
        - xrootd
        - gcc >=4.9.1

    run:
        - python
        - openssl
        - qt
        - sqlite
        - fftw
        - libxml2
        - sqlite
        - gccxml
        - xrootd

test:
    imports:
        - ROOT

    commands:

about:
    home: http://root.cern.ch/
    license: LGPL v2.1

