package:
  name: libxml2
  version: 2.9.2

source:
  fn: libxml2-2.9.2.tar.gz
  url: ftp://xmlsoft.org/libxml2/libxml2-2.9.2.tar.gz

requirements:
  build:
    - gcc >=4.9.1

about:
  home: http://xmlsoft.org
  license: MIT
