package:
  name: qt
  version: 4.8.6

source:
  fn: qt-everywhere-opensource-src-4.8.6.tar.gz
  url: http://download.qt-project.org/official_releases/qt/4.8/4.8.6/qt-everywhere-opensource-src-4.8.6.tar.gz
  sha1: ddf9c20ca8309a116e0466c42984238009525da6
  # https://github.com/Homebrew/homebrew/blob/master/Library/Formula/qt.rb
  patches:
    - qmake-arch.patch
    - acceptance.patch

build:
  number: 0

requirements:
  build:
    - freetype
    - openssl
    - gcc >=4.9.1

about:
    home: http://qt-project.org
    license: LGPL
