package:
  name: boost
  version: 1.56.0

source:
  fn: boost_1_56_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.bz2

build:
  number: 0

requirements:
  build:
    - python
    - gcc >=4.9.1

about:
  home: http://www.boost.org/
  license: Boost-1.0

