package:
  name: tbb
  version: 4.2.5

source:
  fn: tbb42_20140601oss_src.tgz
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb42_20140601oss_src.tgz
  md5: 2968a70d10167310d9890fed7a1c84b1

requirements:
  build:
    - python
    - gcc >=4.9.1

about:
  home: http://www.threadingbuildingblocks.org
  license: GPL v2
